version: '3.9'
services:
    loca7:
        container_name: loca7
        env_file:
            - .env
        environment:
            DATABASE_URL: postgresql://ewen:root@db:5432/loca7
        build: .
        ports:
            - '3000:3000'
        depends_on: [db]
    db:
        container_name: db
        environment:
            POSTGRES_USER: ewen
            POSTGRES_PASSWORD: root
            POSTGRES_DB: loca7
            PGDATA: /data/postgres
        image: postgres:latest
        volumes:
            - postgres:/data/postgres
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: ewen@ewen.works
            PGADMIN_DEFAULT_PASSWORD: root
            PGADMIN_LISTEN_PORT: 80
        ports:
            - 5000:80
        depends_on:
            - db
        volumes:
            - pgadmin:/var/lib/pgadmin

volumes:
    postgres:
    pgadmin:
