version: '3.9'
services:
  db:
    restart: always
    expose:
      - 3306
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loca7
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
      - ./init-dev-db.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data:
    driver: local
